language: scala
sudo: false
jdk: oraclejdk8
scala:
- 2.11.12
- 2.12.8
- 2.13.0-M5
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}" test "scalaParser/testOnly scalaparser.SnippetSpec"
matrix:
  include:
  - scala: 2.11.12
    before_script:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
  - scala: 2.12.8
    jdk: openjdk11
