language: scala
sudo: false
jdk: oraclejdk8
scala:
- 2.11.12
- 2.12.7
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}" test "scalaParser/testOnly scalaparser.SnippetSpec"
matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.7
  - scala: 2.13.0-M5
    script:
    - sbt
      "++ ${TRAVIS_SCALA_VERSION}"
      parboiledCoreJVM/test
      parboiledJVM/test
      "scalaParser/testOnly scalaparser.SnippetSpec"
